### PR TITLE
Fix status checks

### PR DESCRIPTION
**Pull request by julianhille**

### CODE REVIEW

**Comment by julianhille** [comment]
just saw that there are several colons and some of the code is now worse then before. There are some functions like :`picc_read_card_serial` which really returns bools. Sorry for that will retry

**Comment by chme** [comment]
Did you encounter an error?

The `StausCode` enum overrides the `__bool__` method. The change you are proposing should not result in any changed behavior (and therefor not fix any errors).

https://github.com/chme/MFRC522-python/blob/4a1dcc11dd40947674b0c22005c09f6d6d1dc497/mfrc522/mfrc522.py#L439-L440

**Comment by chme** [comment]
I've pushed a simple unit test, that checks if the canceled status is correctly handled: 5d24579d6e6dd96804f8eab92fb735220ebfa390

The canceled interrupt during `readText()` returns correctly `(StatusCode.STATUS_CANCELED, None, None)`.

**Comment by julianhille** [comment]
ah damn it. did not see that. That should work even if its a bit implicit.

Yeah i encountered a lot of ```TypeError: 'NoneType' object is not iterable```
when trying to read

**Comment by julianhille** [comment]
The error happens here https://github.com/chme/MFRC522-python/blob/master/mfrc522/simple_mfrc522.py#L172

But I see that the return value is correct. 
I guess I'm doing something else wrong. 
I use threads and callback hell so maybe I'm doing two reads at the same time from different threads.

**Comment by chme** [comment]
mmh ... `data` gets initialized in `_read_mifare_classic` and should never be `None` at this point.

To avoid different threads accessing the same resources, i experimented with asyncio. I got it working, but the code was imo rather complex and not so easy to follow (might be due to my limited python knowledge). 

What i want to try out is to wrap this library in a program, that sends mqtt messages, if a new card is present. Running that as a daemon hopefully will make it easier to interact with the mfrc522.
If you are interested, i can publish the current state (totally untested :-)

**Pull request closed without merging**
